#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Aug 28 09:38:13 +0200 2023
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm fifo_generator_v13_2_5 xil_defaultlib xlconcat_v2_1_4 axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_24 fit_timer_v2_0_10 axi_intc_v4_1_15 xlconstant_v1_1_7 lib_pkg_v1_0_2 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_subset_converter_v1_1_22 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 v_tc_v6_2_1 axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 proc_sys_reset_v5_0_13 axi_timer_v2_0_24 axi_uartlite_v2_0_26 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ip/system_audio_codec_ctrl_0_0/src/fifo/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ip/system_audio_codec_ctrl_0_0/src/fifo/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ip/system_audio_codec_ctrl_0_0/src/fifo/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_audio_codec_ctrl_0_0/src/fifo/sim/fifo.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/family_support.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/common_types.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/user_logic.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/iis_deser.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/iis_ser.vhd" \
    "$ref_dir/../../../bd/system/ipshared/06b8/src/i2s_ctrl.vhd" \
    "$ref_dir/../../../bd/system/ip/system_audio_codec_ctrl_0_0/sim/system_audio_codec_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0_clk_wiz.v" \
    "$ref_dir/../../../bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_Concat_Interrupts_0/sim/system_Concat_Interrupts_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_btns_gpio_0/sim/system_btns_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fit_timer_v2_0_10 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/e81b/hdl/fit_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_fit_timer_0_0/sim/system_fit_timer_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_leds_gpio_0/sim/system_leds_gpio_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgbleds_gpio_0/sim/system_rgbleds_gpio_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_switches_gpio_0/sim/system_switches_gpio_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_intc_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/47b8/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_user_intc_0/sim/system_user_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconcat_0_0/sim/system_xlconcat_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_0/sim/system_xlconstant_0_0.v" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_dynclk_0/sim/system_axi_dynclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_vdma_0/sim/system_axi_vdma_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tdata_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tuser_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tstrb_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tkeep_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tid_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tdest_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/tlast_system_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/hdl/top_system_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_axis_subset_converter_0_0/sim/system_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_hdmi_out_hpd_video_0/sim/system_hdmi_out_hpd_video_0.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/ClockGen.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/SyncAsync.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/dc1a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rgb2dvi_1_0/sim/system_rgb2dvi_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_v_axi4s_vid_out_0_0/sim/system_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_vtc_out_0/sim/system_vtc_out_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_1/sim/system_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_ps7_0_0/sim/system_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_fclk0_0/sim/system_rst_ps7_0_fclk0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_rst_ps7_0_fclk1_0/sim/system_rst_ps7_0_fclk1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xlconstant_0_2/sim/system_xlconstant_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_conv_funs_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_proc_common_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_ipif_pkg.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family_support.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_family.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_soft_reset.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/proc_common_v3_30_a/hdl/src/vhdl/system_xadc_wiz_0_0_pselect_f.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_address_decoder.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_slave_attachment.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/interrupt_control_v2_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_interrupt_control.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/axi_lite_ipif_v1_01_a/hdl/src/vhdl/system_xadc_wiz_0_0_axi_lite_ipif.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_xadc_core_drp.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_axi_xadc.vhd" \
    "$ref_dir/../../../bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_timer_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/70d6/hdl/axi_timer_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_timer_0_3/sim/system_axi_timer_0_3.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_timer_1_2/sim/system_axi_timer_1_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_timer_0_2/sim/system_axi_timer_0_2.vhd" \
    "$ref_dir/../../../bd/system/ip/system_axi_gpio_0_0/sim/system_axi_gpio_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_arduino_input_0/sim/system_arduino_input_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_uartlite_0_0/sim/system_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_0_0/sim/system_tier2_xbar_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_1_0/sim/system_tier2_xbar_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tier2_xbar_2_0/sim/system_tier2_xbar_2_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/d0f7" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/8713/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ecen427.srcs/sources_1/bd/system/ipshared/34f8/hdl" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_1/sim/system_auto_pc_1.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_98/sim/system_s00_regslice_98.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_9/sim/system_auto_pc_9.v" \
    "$ref_dir/../../../bd/system/ip/system_m00_regslice_0/sim/system_m00_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m01_regslice_0/sim/system_m01_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m02_regslice_0/sim/system_m02_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m03_regslice_0/sim/system_m03_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m04_regslice_0/sim/system_m04_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m05_regslice_0/sim/system_m05_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m06_regslice_0/sim/system_m06_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m07_regslice_0/sim/system_m07_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_m08_regslice_0/sim/system_m08_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_2/sim/system_auto_pc_2.v" \
    "$ref_dir/../../../bd/system/ip/system_m09_regslice_0/sim/system_m09_regslice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_3/sim/system_auto_pc_3.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_4/sim/system_auto_pc_4.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_5/sim/system_auto_pc_5.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_6/sim/system_auto_pc_6.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_7/sim/system_auto_pc_7.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_8/sim/system_auto_pc_8.v" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_10/sim/system_auto_pc_10.v" \
    "$ref_dir/../../../bd/system/ip/system_s00_regslice_99/sim/system_s00_regslice_99.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/sim/system.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
