# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.runs/synth_1/system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.cache/wt [current_project]
set_property parent.project_path C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]
set_property ip_repo_paths c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.ipdefs/digilent_ip [current_project]
update_ip_catalog
set_property ip_output_repo c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/hdl/system_wrapper.vhd
add_files C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_audio_codec_ctrl_0_0/src/fifo/fifo.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_clk_wiz_10MHz_0/system_clk_wiz_10MHz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_btns_gpio_0/system_btns_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_fit_timer_0_0/system_fit_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_leds_gpio_0/system_leds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_leds_gpio_0/system_leds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_leds_gpio_0/system_leds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgbleds_gpio_0/system_rgbleds_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_switches_gpio_0/system_switches_gpio_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_switches_gpio_0/system_switches_gpio_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_switches_gpio_0/system_switches_gpio_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_user_intc_0/system_user_intc_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_user_intc_0/system_user_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_user_intc_0/system_user_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_vdma_0/system_axi_vdma_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axis_subset_converter_0_0/system_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_hdmi_out_hpd_video_0/system_hdmi_out_hpd_video_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rgb2dvi_1_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_v_axi4s_vid_out_0_0/system_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_vtc_out_0/system_vtc_out_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_vtc_out_0/system_vtc_out_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_ps7_0_0/system_ps7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk0_0/system_rst_ps7_0_fclk0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk0_0/system_rst_ps7_0_fclk0_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk0_0/system_rst_ps7_0_fclk0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk1_0/system_rst_ps7_0_fclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk1_0/system_rst_ps7_0_fclk1_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_rst_ps7_0_fclk1_0/system_rst_ps7_0_fclk1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_xadc_wiz_0_0/system_xadc_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_0_3/system_axi_timer_0_3.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_0_3/system_axi_timer_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_0_2/system_axi_timer_0_2.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_0_2/system_axi_timer_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_arduino_input_0/system_arduino_input_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_arduino_input_0/system_arduino_input_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_arduino_input_0/system_arduino_input_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_uartlite_0_0/system_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_1_0/system_tier2_xbar_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_2_0/system_tier2_xbar_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_s00_regslice_100/system_s00_regslice_100_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_s00_regslice_100/system_s00_regslice_100_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_9/system_auto_pc_9_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m00_regslice_0/system_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m02_regslice_0/system_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m03_regslice_0/system_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m03_regslice_0/system_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m04_regslice_0/system_m04_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m04_regslice_0/system_m04_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m05_regslice_0/system_m05_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m05_regslice_0/system_m05_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m06_regslice_0/system_m06_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m06_regslice_0/system_m06_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m07_regslice_0/system_m07_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m07_regslice_0/system_m07_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m08_regslice_0/system_m08_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m08_regslice_0/system_m08_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m09_regslice_0/system_m09_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_m09_regslice_0/system_m09_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_4/system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_5/system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_6/system_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_7/system_auto_pc_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_8/system_auto_pc_8_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_auto_pc_10/system_auto_pc_10_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_s00_regslice_101/system_s00_regslice_101_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_s00_regslice_101/system_s00_regslice_101_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/constrs_1/imports/constraints/top.xdc
set_property used_in_implementation false [get_files C:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/constrs_1/imports/constraints/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_wrapper -part xc7z020clg400-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
