# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2.xci
# IP: The module: 'system_axi_timer_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_1_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2.xci
# IP: The module: 'system_axi_timer_1_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/sources/S3_ES_Fall-23/ES_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_axi_timer_1_2/system_axi_timer_1_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_1_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
