# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
# IP: The module: 'system_tier2_xbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tier2_xbar_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0.xci
# IP: The module: 'system_tier2_xbar_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/S3_ES_Fall-23/ES1_PYNQ_Z2_Ref/ecen427_v0.4/ecen427.srcs/sources_1/bd/system/ip/system_tier2_xbar_0_0/system_tier2_xbar_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tier2_xbar_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
